version: "3"

services:
  postgres:
    image: "postgres:17.0"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: polls
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5432:5432"
